const usernames = [
    'cindypineapple',
    'dopeydolphins',
    'sillyseals',
    'bigbears',
    'happyhippos',
    'sleepysquirrels',
    'funnyfoxes',
    'lazyllamas',
    'hungryhogs',
    'sillystorks',
    'playfulpigeons',
    'awesomealligators',
    'gentlegoats',
    'chattychimps',
    'busybees'
  ];
  
  const emails = [
    'cindypineapple@example.com',
    'dopeydolphins@example.com',
    'sillyseals@example.com',
    'bigbears@example.com',
    'happyhippos@example.com',
    'sleepysquirrels@example.com',
    'funnyfoxes@example.com',
    'lazyllamas@example.com',
    'hungryhogs@example.com',
    'sillystorks@example.com',
    'playfulpigeons@example.com',
    'awesomealligators@example.com',
    'gentlegoats@example.com',
    'chattychimps@example.com',
    'busybees@example.com'
  ];


  const thoughtText = [
    'I found this great article about the benefits of blogging. It was incredibly informative and I highly recommend it!',
    'I just wrote a blog post about the importance of staying organized. Check it out if you want to learn more!',
    'I wrote a blog post about the power of positive thinking. Read it to learn more about this amazing topic!',
    'I wrote a blog post on how to make the most out of every day. Check it out if you want to become more productive!',
    'I recently wrote a blog post about the benefits of living an active lifestyle. Read it to learn more!',
    'I just wrote a blog post about the importance of having a balanced diet. Check it out if you want to learn more!',
    'I wrote a blog post on the importance of taking breaks to recharge. Read it to learn more about this amazing topic!',
    'I wrote a blog post about the power of goal setting. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the importance of learning from failure. Check it out if you want to learn more!',
    'I recently wrote a blog post about how to stay motivated. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the power of networking. Check it out if you want to learn more!',
    'I wrote a blog post about the importance of self-care. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the power of resilience. Check it out if you want to learn more!',
    'I recently wrote a blog post about how to overcome obstacles. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the importance of nurturing relationships. Check it out if you want to learn more!',
    'I wrote a blog post on how to be a better listener. Read it to learn more about this amazing topic!',
    'I wrote a blog post about the power of positivity. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the importance of having a growth mindset. Check it out if you want to learn more!',
    'I recently wrote a blog post about how to practice mindfulness. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the power of having a good attitude. Check it out if you want to learn more!',
    'I wrote a blog post about the importance of having a strong work ethic. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the power of taking risks. Check it out if you want to learn more!',
    'I recently wrote a blog post about how to be a better leader. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the importance of self-reflection. Check it out if you want to learn more!',
    'I wrote a blog post on how to stay focused. Read it to learn more about this amazing topic!',
    'I wrote a blog post about the power of visualizing success. Read it to learn more about this amazing topic!',
    'I just wrote a blog post about the importance of being creative. Check it out if you want to learn more!',
    'I recently wrote a blog post about how to develop a growth mindset. Read it to learn more about this amazing topic!'
  ];


  const reactions = [
    'Great post!',
    'Love it!',
    'Very inspiring!',
    'Love the tips!',
    'Fantastic advice!',
    'This is great!',
    'Amazing post!',
    'Well written!',
    'Inspiring stuff!',
    'Good advice!',
    'So true!',
    'Helpful tips!',
    'Very helpful!',
    'Thanks for sharing!',
    'Very informative!',
    'Very insightful!',
    'Love the advice!',
    'This is so true!',
    'So inspiring!',
    'Great read!',
    'Super helpful!',
    'Thanks for the post!',
    'This is awesome!',
    'Fabulous advice!',
    'Good tips!',
    'Well said!',
    'Great insights!',
    'Very motivating!',
    'Very encouraging!',
    'Interesting read!',
    'Nice post!',
    'Good read!',
    'Interesting insight!',
    'This is amazing!',
    'Very useful!',
    'Wonderful read!',
    'This is helpful!',
    'Very useful advice!',
    'Love the read!',
    'Inspiring stuff!',
    'Very encouraging!',
    'Very enlightening!',
    'Nice insights!',
    'Good tips!',
    'Love the tips!',
    'This is brilliant!',
    'Fabulous read!',
    'Very informative!',
    'Great advice!',
    'Love the advice!',
    'Very thought-provoking!',
    'So inspiring!',
    'Very interesting!',
    'Thanks for the tips!',
    'This is useful!',
    'Great read!',
    'Very useful advice!',
    'Love the insights!',
    'Inspiring post!',
    'This is fantastic!',
    'Very valuable advice!',
    'Nice advice!',
    'Interesting read!',
    'This is great!',
    'Love the post!',
    'Very motivating!',
    'Very helpful!',
    'Useful tips!',
    'Wonderful post!',
    'This is helpful!',
    'Good insights!',
    'Helpful read!',
    'Very valuable!',
    'Thanks for the advice!',
    'Love the read!',
    'Very insightful!',
    'Lovely post!',
    'Great tips!'
  ];
